[build]
  # Build command
  command = "npm run build"

  # Directory to publish (relative to base directory)
  publish = "dist"

# Environment variables for production
[build.environment]
  NODE_VERSION = "22"
  NODE_ENV = "development"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self)"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service Worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Exclude static assets from redirect
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/favicon*"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/logo*"
  to = "/logo.png"
  status = 200

[[redirects]]
  from = "/manifest*"
  to = "/manifest.webmanifest"
  status = 200

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

[[redirects]]
  from = "/registerSW.js"
  to = "/registerSW.js"
  status = 200

[[redirects]]
  from = "/workbox*"
  to = "/workbox-*.js"
  status = 200
