services:
  # Frontend Service
  - type: web
    name: rush-delivery-frontend
    env: static
    plan: free
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: rush-delivery-backend
          property: host
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_GA_ID
        sync: false
      - key: NODE_ENV
        value: production

  # Backend Service
  - type: web
    name: rush-delivery-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://rush-delivery-frontend.onrender.com,https://rushdelivery.netlify.app
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: .
